apiVersion: apps/v1
kind: Deployment
metadata:
  name: "myecommerceapp-cartservice"
  labels:
    app: "myecommerceapp-cartservice"
spec:
  selector:
    matchLabels:
      app: "myecommerceapp-cartservice"
  template:
    metadata:
      labels:
        app: "myecommerceapp-cartservice"
    spec:
      terminationGracePeriodSeconds: 5
      containers:
        - name: server
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: true
          image: us-central1-docker.pkg.dev/google-samples/microservices-demo/cartservice:v0.10.2
          ports:
            - containerPort: 7070
          env:
            - name: REDIS_ADDR
              value: "redis-cart:6379"
          resources:
            requests:
              cpu: 200m
              memory: 64Mi
            limits:
              cpu: 300m
              memory: 128Mi
          readinessProbe:
            initialDelaySeconds: 15
            grpc:
              port: 7070
          livenessProbe:
            initialDelaySeconds: 15
            periodSeconds: 10
            grpc:
              port: 7070
---
apiVersion: v1
kind: Service
metadata:
  name: "myecommerceapp-cartservice"
  labels:
    app: "myecommerceapp-cartservice"
spec:
  type: ClusterIP
  selector:
    app: "myecommerceapp-cartservice"
  ports:
    - name: grpc
      port: 7070
      targetPort: 7070
