apiVersion: apps/v1
kind: Deployment
metadata:
  name: "myecommerceapp-currencyservice"
  labels:
    app: "myecommerceapp-currencyservice"
spec:
  selector:
    matchLabels:
      app: "myecommerceapp-currencyservice"
  template:
    metadata:
      labels:
        app: "myecommerceapp-currencyservice"
    spec:
      terminationGracePeriodSeconds: 5
      containers:
        - name: server
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: true
          image: us-central1-docker.pkg.dev/google-samples/microservices-demo/currencyservice:v0.10.2
          ports:
            - name: grpc
              containerPort: 7000
          env:
            - name: PORT
              value: "7000"
            - name: DISABLE_PROFILER
              value: "1"
          readinessProbe:
            grpc:
              port: 7000
          livenessProbe:
            grpc:
              port: 7000
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: "myecommerceapp-currencyservice"
  labels:
    app: "myecommerceapp-currencyservice"
spec:
  type: ClusterIP
  selector:
    app: "myecommerceapp-currencyservice"
  ports:
    - name: grpc
      port: 7000
      targetPort: 7000
