apiVersion: apps/v1
kind: Deployment
metadata:
  name: "myecommerceapp-emailservice"
  labels:
    app: "myecommerceapp-emailservice"
spec:
  selector:
    matchLabels:
      app: "myecommerceapp-emailservice"
  template:
    metadata:
      labels:
        app: "myecommerceapp-emailservice"
    spec:
      terminationGracePeriodSeconds: 5
      containers:
        - name: server
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
          image: us-central1-docker.pkg.dev/google-samples/microservices-demo/emailservice:v0.10.2
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
            - name: DISABLE_PROFILER
              value: "1"
          readinessProbe:
            periodSeconds: 5
            grpc:
              port: 8080
          livenessProbe:
            periodSeconds: 5
            grpc:
              port: 8080
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: "myecommerceapp-emailservice"
  labels:
    app: "myecommerceapp-emailservice"
spec:
  type: ClusterIP
  selector:
    app: "myecommerceapp-emailservice"
  ports:
    - name: grpc
      port: 5000
      targetPort: 8080
