apiVersion: apps/v1
kind: Deployment
metadata:
  name: "myecommerceapp-productcatalogservice"
  labels:
    app: "myecommerceapp-productcatalogservice"
spec:
  selector:
    matchLabels:
      app: "myecommerceapp-productcatalogservice"
  template:
    metadata:
      labels:
        app: "myecommerceapp-productcatalogservice"
    spec:
      terminationGracePeriodSeconds: 5
      containers:
        - name: server
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: true
          image: us-central1-docker.pkg.dev/google-samples/microservices-demo/productcatalogservice:v0.10.2
          ports:
            - containerPort: 3550
          env:
            - name: PORT
              value: "3550"
            - name: DISABLE_PROFILER
              value: "1"
          readinessProbe:
            grpc:
              port: 3550
          livenessProbe:
            grpc:
              port: 3550
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: "myecommerceapp-productcatalogservice"
  labels:
    app: "myecommerceapp-productcatalogservice"
spec:
  type: ClusterIP
  selector:
    app: "myecommerceapp-productcatalogservice"
  ports:
    - name: grpc
      port: 3550
      targetPort: 3550
